name: Build & Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/anishamidi/exchange:latest .

    - name: Push Docker image
      run: docker push ghcr.io/anishamidi/exchange:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/django-deployment django=ghcr.io/anishamidi/exchange:latest
        kubectl rollout status deployment/django-deployment

