name: Build & Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, macOS, ARM64]  

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/anishamidi/exchange:latest .

      - name: Push Docker image
        run: docker push ghcr.io/anishamidi/exchange:latest

      - name: Ensure kubectl is installed
        run: |
          if ! command -v kubectl &> /dev/null; then
            brew install kubectl
          fi

      - name: Test Minikube connection
        run: |
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/django django=ghcr.io/anishamidi/exchange:latest
          kubectl rollout status deployment/django

